const PlayerApi = [
  {
    default: true,
    duration: "7",
    winloss: 3.35,
    deposited: 5,
    depositedAvarage: 14,
    withdrawn: 100,
    withdrawnAvarage: 150,
    daysPlaying: 6,
    daysPlayingAvarage: 7,
    playingDuration: 7.5,
    playingDurationAvarage: 13.2,
  },
  {
    default: false,
    duration: "30",
    winloss: 33.35,
    deposited: 55,
    depositedAvarage: 77,
    withdrawn: 130,
    withdrawnAvarage: 250,
    daysPlaying: 16,
    daysPlayingAvarage: 17,
    playingDuration: 10.5,
    playingDurationAvarage: 16.2,
  },
  {
    default: false,
    duration: "90",
    winloss: 66.35,
    deposited: 77,
    depositedAvarage: 177,
    withdrawn: 300,
    withdrawnAvarage: 350,
    daysPlaying: 38,
    daysPlayingAvarage: 97,
    playingDuration: 14.5,
    playingDurationAvarage: 22.2,
  },
  {
    default: false,
    duration: "180",
    winloss: 39.35,
    deposited: 122,
    depositedAvarage: 144,
    withdrawn: 400,
    withdrawnAvarage: 450,
    daysPlaying: 126,
    daysPlayingAvarage: 137,
    playingDuration: 44.5,
    playingDurationAvarage: 77.2,
  },
];

export default PlayerApi